version: '3.7'
services:
  venarimaster:
    image: ${VENARI_IMAGE:-assertsecurity.azurecr.io/venari:3.5}
    volumes:
      - nodedata:/Data
      - userdb:/local-storage
    ports:
      - "9000:9000"
    command:
      - "--logging:loglevel:default=warning"
      - "--connectionStrings:userDatabase=Data Source=/local-storage/venari-users.db"

      - "--node:disablejobqueue=true"
      - "--node:analyzerinprocess=false"
      - "--node:useHttps=true"
      - "--node:RootAppDataDirectoryOverride=/Data"
      - "--node:ListenAnyAddress=true"

      - "--server:loglevel=info"
      - "--server:tlsPort=9000"
      - "--server:deleteRulesOnStartup=false"
      - "--server:NodeHubTimeoutSeconds=300"
      - "--server:ignorecerterrors=true"

      - "--identity:adminUserName=${ADMIN_EMAIL}"
      - "--identity:publicUrl=${PUBLIC_MASTER_BASEURL}:${PUBLIC_MASTER_PORT}"

      - "--identity:local:enabled=true"
      - "--identity:local:allowedIssuers:0=${PUBLIC_MASTER_BASEURL}:${PUBLIC_MASTER_PORT}/"
      - "--identity:local:allowedIssuers:1=https://venarimaster:9000/"
      - "--identity:local:redirectUris:0=${PUBLIC_MASTER_BASEURL}:${PUBLIC_MASTER_PORT}/index.html"
      - "--identity:local:redirectUris:1=${PUBLIC_MASTER_BASEURL}:${PUBLIC_MASTER_PORT}/silent-refresh.html"
      - "--identity:local:redirectUris:2=${PUBLIC_MASTER_BASEURL}:${PUBLIC_MASTER_PORT}/download"
      - "--identity:local:PostLogouttUris:0=${PUBLIC_MASTER_BASEURL}:${PUBLIC_MASTER_PORT}/index.html"

      - "--identity:external:0:Name=OKTA"
      - "--identity:external:0:enabled=false"
      - "--identity:external:0:authority=<INSERT_OKTA_AUTHORITY>"
      - "--identity:external:0:clientid=<INSERT_OKTA_CLIENTID"
      - "--identity:external:0:scope=openid offline_access profile email"

      - "--bootstrapAccounts:generateJobNodeSecretToFile=/Data/venari-jobnode-login.txt"
      - "--bootstrapAccounts:serviceAccounts:0:clientId=jobnode"
      - "--bootstrapAccounts:serviceAccounts:0:scope=jobnode"
      - "--bootstrapAccounts:serviceAccounts:0:secret=file:///Data/venari-jobnode-login.txt"
      - "--bootstrapAccounts:serviceAccounts:0:displayName=DevOps Job Node"
    environment:
      node__nodename: "venarimaster"
    networks:
      venari:
        aliases:
          - venarimaster
  jobnode:
    image: ${VENARI_IMAGE:-assertsecurity.azurecr.io/venari:3.5}
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '${JOBNODE_CPU}'
          memory: ${JOBNODE_MEMORY}
        reservations:
          cpus: '${JOBNODE_CPU}'
          memory: ${JOBNODE_MEMORY}
    volumes:
      - nodedata:/Data
      - type: tmpfs
        target: /dev/shm
        tmpfs:
           size: 1073741824
    command:
      - "--logging:loglevel:default=warning"
      - "--node:masterNodeBaseAddress=https://venarimaster:9000"
      - "--node:analyzerinprocess=false"
      - "--node:RootAppDataDirectoryOverride=/Data"
      - "--server:loglevel=info"
      - "--server:NodeHubTimeoutSeconds=300"
      - "--server:ignorecerterrors=true"
      - "--node:authInfo:clientId=jobnode"
      - "--node:authInfo:clientSecret=file:///Data/venari-jobnode-login.txt"
      - "--node:authInfo:scope=jobnode"
    networks:
      venari:
volumes:
  nodedata:
    name: venari-devops
  userdb:
    name: venari-userdb #Important! Make sure this is not on a volume backed by a network share (i.e. nfs)
networks:
  venari:

    
