kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pv-orchestrator-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: pv-orchestrator-storage-class
