apiVersion: v1
kind: Service
metadata:
  name: {{ include "venari-devops-controller.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "venari-devops-controller.name" . }}
    helm.sh/chart: {{ include "venari-devops-controller.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      nodePort: null
      name: controller
  selector:
    app.kubernetes.io/name: {{ include "venari-devops-controller.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}