kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pv-jobnode-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: pv-jobnode-storage-class
