# Default values for venari-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


image:
  repository: ""
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

jobnode:
  containerPort: 443
  replicaCount: 1
  args: 
    - "--logging:loglevel:default=warning"
    - "--node:analyzerinprocess=false"
    - "--node:RootAppDataDirectoryOverride=/Data"
    - "--server:tlsPort=443"
    - "--server:loglevel=info"
    - "--server:NodeHubTimeoutSeconds=300"
    - "--server:ignorecerterrors=true"
    - "--node:authInfo:clientId=jobnode"
    - "--node:authInfo:scope=jobnode"
  resources:
    enabled: false
    limits:
      cpu: '6'
      memory: 16Gi
    requests:
      cpu: '6'
      memory: 16Gi
  allowedJobNodeCount: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

ingress:
  enabled: false
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hostName: ""

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

service:
  port: 443
  type: NodePort

persistence:
  existingClaim: ""
  allowedJobNodeCount: ""

secrets:
  secretsDir: "/etc/secrets"
